In [33]:
import numpy as np
from numpy.random import default_rng

RNG = default_rng(seed=0)

def sigmoid(a):
    return 1/(1+np.exp(-a))

n = 100
d = 10
beta = RNG.normal(size=d+1)
x = RNG.multivariate_normal(np.zeros(shape=(d, )), np.eye(d), size=n)
x = np.column_stack((np.ones(dtype=float, shape=n), x))
y = RNG.binomial(n=1, p=sigmoid(x.dot(beta)))

In [34]:
import statsmodels.api as sm

lr = sm.GLM(y, x, family=sm.families.Binomial())
res = lr.fit()
res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:                      y   No. Observations:                  100
Model:                            GLM   Df Residuals:                       89
Model Family:                Binomial   Df Model:                           10
Link Function:                  Logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -33.068
Date:                Fri, 10 Jun 2022   Deviance:                       66.137
Time:                        17:32:17   Pearson chi2:                     111.
No. Iterations:                     7   Pseudo R-squ. (CS):             0.5139
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.1276      0.339      0.376      0.707      -0.537       0.792
x1             0.2948      0.389      0.758      0.449      -0.468       1.058
x2             0.7304      0.375      1.947      0.052      -0.005       1.466
x3             0.1989      0.321      0.619      0.536      -0.431       0.829
x4            -0.4685      0.355     -1.320      0.187      -1.164       0.227
x5            -0.0845      0.393     -0.215      0.830      -0.854       0.685
x6             2.2185      0.603      3.680      0.000       1.037       3.400
x7             1.6919      0.496      3.412      0.001       0.720       2.664
x8            -1.2243      0.387     -3.166      0.002      -1.982      -0.466
x9            -2.5337      0.665     -3.808      0.000      -3.838      -1.230
x10           -0.4370      0.328     -1.331      0.183      -1.081       0.207
==============================================================================
"""

In [36]:
beta

array([ 0.12573022, -0.13210486,  0.64042265,  0.10490012, -0.53566937,
        0.36159505,  1.30400005,  0.94708096, -0.70373524, -1.26542147,
       -0.62327446])

In [35]:
res.params - beta

array([ 0.00187527,  0.42690541,  0.08994432,  0.0939947 ,  0.06719477,
       -0.44606805,  0.91452938,  0.74484874, -0.52054952, -1.26831935,
        0.18627536])

In [37]:
res.predict(x)

array([3.05421534e-03, 4.38569126e-02, 2.63360661e-03, 9.22168375e-01,
       9.97314553e-01, 9.99988279e-01, 7.36173432e-03, 5.60398693e-01,
       9.86145589e-01, 7.83068541e-01, 4.83998697e-01, 7.88873068e-01,
       9.95233805e-01, 3.87509883e-03, 9.99359471e-01, 2.31071365e-04,
       8.95450513e-01, 9.64525731e-01, 1.91909051e-02, 1.99388862e-03,
       7.13176630e-04, 9.91071833e-01, 8.96033043e-01, 9.98621342e-01,
       3.82891474e-03, 5.10564488e-01, 3.38347222e-02, 2.88830103e-02,
       3.76191959e-01, 7.33148103e-02, 5.52348527e-02, 4.00900118e-01,
       8.98319312e-01, 1.32563251e-01, 2.14523205e-02, 4.24870987e-01,
       8.74745657e-01, 2.26671400e-02, 4.34035186e-01, 4.32353535e-01,
       5.18810574e-01, 9.32580632e-02, 6.77894363e-01, 2.67310651e-01,
       4.41603940e-01, 2.35497245e-01, 8.70319770e-01, 6.03876012e-02,
       6.51939090e-01, 5.10844142e-01, 9.99873989e-01, 4.34077205e-01,
       9.52312986e-01, 3.51712994e-01, 5.10403816e-02, 9.81426814e-01,
      

In [38]:
np.where(res.predict(x)>=0.5, 1, 0)

array([0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1])

In [39]:
np.column_stack((1-res.predict(x), res.predict(x)))

array([[9.96945785e-01, 3.05421534e-03],
       [9.56143087e-01, 4.38569126e-02],
       [9.97366393e-01, 2.63360661e-03],
       [7.78316250e-02, 9.22168375e-01],
       [2.68544675e-03, 9.97314553e-01],
       [1.17207273e-05, 9.99988279e-01],
       [9.92638266e-01, 7.36173432e-03],
       [4.39601307e-01, 5.60398693e-01],
       [1.38544110e-02, 9.86145589e-01],
       [2.16931459e-01, 7.83068541e-01],
       [5.16001303e-01, 4.83998697e-01],
       [2.11126932e-01, 7.88873068e-01],
       [4.76619501e-03, 9.95233805e-01],
       [9.96124901e-01, 3.87509883e-03],
       [6.40529488e-04, 9.99359471e-01],
       [9.99768929e-01, 2.31071365e-04],
       [1.04549487e-01, 8.95450513e-01],
       [3.54742688e-02, 9.64525731e-01],
       [9.80809095e-01, 1.91909051e-02],
       [9.98006111e-01, 1.99388862e-03],
       [9.99286823e-01, 7.13176630e-04],
       [8.92816713e-03, 9.91071833e-01],
       [1.03966957e-01, 8.96033043e-01],
       [1.37865831e-03, 9.98621342e-01],
       [9.961710

In [40]:
from sklearn.linear_model import LogisticRegression

lr_sklearn = LogisticRegression(penalty='none', fit_intercept=False)
lr_sklearn.fit(x, y)
lr_sklearn.coef_

array([[ 0.12760852,  0.29479784,  0.7303651 ,  0.19887894, -0.46848642,
        -0.08446892,  2.21852928,  1.69193243, -1.22427505, -2.53373726,
        -0.43699864]])

In [41]:
res.params

array([ 0.12760549,  0.29480055,  0.73036697,  0.19889482, -0.46847461,
       -0.08447299,  2.21852942,  1.6919297 , -1.22428476, -2.53374082,
       -0.43699911])